name: 'package python-3.7 dependencies for aws lambda'
description: 'Build a zip archive from requirements.txt'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.package_name}}